### ISSUE TITLE
The 390 driver won't work here

### ISSUE THREAD

**Issue by Laser-Cat** [jonathonf/manjaro-nvidia#2]
Can't start SDDM
got the following from dmesg
...
[  290.161165] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  290.379701] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  290.595953] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  290.868199] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  291.093588] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  291.360143] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
[  291.592402] nvidia: version magic '4.14.15-1-MANJARO SMP preempt mod_unload modversions retpoline ' should be '4.14.15-1-MANJARO SMP preempt mod_unload modversions '
...

Neither the 378 I downloaded earliar works....
Similiar bug with the version magic stuff...
I built those right after I fully updated my system with pacman -Syyu....

build script 

cd nvidia-utils
makepkg -Csrc
sudo pacman -Udd *pkg*xz

cd ../lib32-nvidia-utils
makepkg -Csrc
sudo pacman -Udd *pkg*xz

cd ../nvidia-414
makepkg -Csric
sudo pacman -Udd *pkg*xz

Turns out the culprit is likely the 4.14 kernel.
The 387 driver built for linux415 worked happily...

**Comment by jonathonf** [comment]
The kernel 4.14.15 in **stable** is built with a GCC without `retpoline` patches. However, GCC in **stable** has `retpoline` support so modules you compile won't load in that kernel.

This isn't a package issue.

**Comment by Laser-Cat** [comment]
Understood , thanks~
