### ISSUE TITLE
[Testing] Driver on 4.15 looks good so far

### ISSUE THREAD

**Issue by rporter220** [jonathonf/manjaro-nvidia#3]
I found this github with an old thread on the forums and was interested since the 390.25 driver is supposed to improve performance.

I have applied this to my Manjaro KDE environment and I'm not having any stability issues with the system, even under heavy workloads. Also, KDE is performing/responding MUCH better with the new driver. Previously I could notice slight hesitation with the animations and running the FPS Gauge in KDE you could see irregular framerates with animations. Now it's sitting at 60fps solid with no drops (v synced to monitor).

Note: I do use the
```
export __KWIN_TRIPLE_BUFFER=1
```
in the /etc/profile.d/kwin.sh 

I have also noticed a noticeable improvement in Vulkan performance with this driver. Testing this I was using DOOM 2016 in Vulkan mode with Wine-Staging 2.21.

So far, this seems to be the best Nvidia driver release in awhile and I think will make many people happy.

Thank you for posting this as I never trust the driver package directly from Nvidia... Has totally burned me in the past. Do you keep this updated as I notice you have the beta drivers branch as well (which I sometimes like to test and can help in certain situations).

I posted this here instead of the Manjaro Forums because I didn't want people seeing this and running out to apply this and causing problems on their system. There has been enought issues with all the retpoline stuff that I didn't want to add anything to your plates. I was just hoping to give you real-world test results that I was seeing since I know XFCE is the "main" edition but I'm running the KDE edition. :-)

If it helps, inxi output:
```
System:    Host: ManjaroKDE Kernel: 4.15.0-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.11.5
           Distro: Manjaro Linux
Machine:   Device: desktop System: Gigabyte product: Z170MX-Gaming 5 serial: N/A
           Mobo: Gigabyte model: Z170MX-Gaming 5 v: x.x serial: N/A
           UEFI: American Megatrends v: F22c date: 12/01/2017
Battery    hidpp__0: charge: N/A condition: NA/NA Wh
CPU:       Quad core Intel Core i5-6600K (-MCP-) cache: 6144 KB
           clock speeds: max: 3900 MHz 1: 2446 MHz 2: 2477 MHz 3: 3000 MHz 4: 3292 MHz
Graphics:  Card: NVIDIA GM200 [GeForce GTX 980 Ti]
           Display Server: N/A driver: nvidia tty size: 115x33
Audio:     Card-1 Intel Sunrise Point-H HD Audio driver: snd_hda_intel Sound: ALSA v: k4.15.0-1-MANJARO
           Card-2 NVIDIA GM200 High Definition Audio driver: snd_hda_intel
Network:   Card: Qualcomm Atheros Killer E220x Gigabit Ethernet Controller driver: alx
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: 40:8d:5c:56:b3:ef
Drives:    HDD Total Size: 2000.4GB (28.0% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 500.1GB
           ID-2: /dev/sdc model: Samsung_SSD_850 size: 500.1GB
           ID-3: /dev/sdb model: ST1000DM003 size: 1000.2GB
Partition: ID-1: / size: 458G used: 203G (47%) fs: ext4 dev: /dev/dm-2
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C gpu: 43C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 190 Uptime: 2:01 Memory: 3204.0/15999.3MB Init: systemd Client: Shell (zsh) inxi: 2.3.56 
```

**Comment by rporter220** [comment]
I saw that these were pulled into the unstable branch. 
I switched branches to unstable and grabbed just the kernels, extra modules, and nvidia utilities and rebooted and everything looks good. 👍

**Comment by jonathonf** [comment]
> Do you keep this updated as I notice you have the beta drivers branch as well

I intend to - there are plenty of people who want the very latest drivers and these packages at least make it easier to manage and remove than the NVIDIA driver bundles.

> I switched branches to unstable and grabbed just the kernels, extra modules, and nvidia utilities and rebooted and everything looks good.

When things work, they work. :)
